AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcCidr:
    Type: 'String'
    Default: '10.0.0.0/16'

  PublicSubnet0Cidr:
    Type: 'String'
    Default: '10.0.0.0/24'
  PublicSubnet1Cidr:
    Type: 'String'
    Default: '10.0.1.0/24'
  PublicSubnet2Cidr:
    Type: 'String'
    Default: '10.0.2.0/24'

  PrivateSubnet0Cidr:
    Type: 'String'
    Default: '10.0.10.0/24'
  PrivateSubnet1Cidr:
    Type: 'String'
    Default: '10.0.11.0/24'
  PrivateSubnet2Cidr:
    Type: 'String'
    Default: '10.0.12.0/24'

  DatabaseSubnet0Cidr:
    Type: 'String'
    Default: '10.0.20.0/24'
  DatabaseSubnet1Cidr:
    Type: 'String'
    Default: '10.0.21.0/24'
  DatabaseSubnet2Cidr:
    Type: 'String'
    Default: '10.0.22.0/24'

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      Tags:
      - Key: Name
        Value: ${AWS::StackName}-vpc
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: ${AWS::StackName}-igw
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref InternetGateway
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: AttachGateway
    Properties:
      VpcId: !Ref Vpc
      Tags:
      - Key: Name
        Value: ${AWS::StackName}-PublicRoute
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet0:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      CidrBlock: !Ref PublicSubnet0Cidr
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: 'true'
      VpcId: !Ref Vpc
      Tags:
      - Key: Name
        Value: ${AWS::StackName}-public-sbn0
  PublicSubnet0RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet0
      RouteTableId: !Ref PublicRouteTable
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      CidrBlock: !Ref PublicSubnet1Cidr
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: 'true'
      VpcId: !Ref Vpc
      Tags:
      - Key: Name
        Value: ${AWS::StackName}-public-sbn1
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      CidrBlock: !Ref PublicSubnet2Cidr
      AvailabilityZone: !Select [2, !GetAZs '']
      MapPublicIpOnLaunch: 'true'
      VpcId: !Ref Vpc
      Tags:
      - Key: Name
        Value: ${AWS::StackName}-public-sbn2
  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  PrivateSubnet0:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      CidrBlock: !Ref PrivateSubnet0Cidr
      AvailabilityZone: !Select [0, !GetAZs '']
      VpcId: !Ref Vpc
      Tags:
      - Key: Name
        Value: ${AWS::StackName}-private-sbn0
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      CidrBlock: !Ref PrivateSubnet1Cidr
      AvailabilityZone: !Select [1, !GetAZs '']
      VpcId: !Ref Vpc
      Tags:
      - Key: Name
        Value: ${AWS::StackName}-private-sbn1
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      CidrBlock: !Ref PrivateSubnet2Cidr
      AvailabilityZone: !Select [2, !GetAZs '']
      VpcId: !Ref Vpc
      Tags:
      - Key: Name
        Value: ${AWS::StackName}-private-sbn2

  DatabaseSubnet0:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      CidrBlock: !Ref DatabaseSubnet0Cidr
      AvailabilityZone: !Select [0, !GetAZs '']
      VpcId: !Ref Vpc
      Tags:
      - Key: Name
        Value: ${AWS::StackName}-database-sbn0
  DatabaseSubnet1:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      CidrBlock: !Ref DatabaseSubnet1Cidr
      AvailabilityZone: !Select [1, !GetAZs '']
      VpcId: !Ref Vpc
      Tags:
      - Key: Name
        Value: ${AWS::StackName}-database-sbn1
  DatabaseSubnet2:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      CidrBlock: !Ref DatabaseSubnet2Cidr
      AvailabilityZone: !Select [2, !GetAZs '']
      VpcId: !Ref Vpc
      Tags:
      - Key: Name
        Value: ${AWS::StackName}-database-sbn2
Outputs:
  Vpc:
    Value: !Ref Vpc
    Export:
      Name: !Sub "${AWS::StackName}-vpc"
  PublicSubnet0:
    Value: !Ref PublicSubnet0
    Export:
      Name: !Sub "${AWS::StackName}-public-sbn0"
  PublicSubnet1:
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub "${AWS::StackName}-public-sbn1"
  PublicSubnet2:
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-public-sbn2"
  PrivateSubnet0:
    Value: !Ref PrivateSubnet0
    Export:
      Name: !Sub "${AWS::StackName}-private-sbn0"
  PrivateSubnet1:
    Value: !Ref PrivateSubnet1
    Export:
      Name: !Sub "${AWS::StackName}-private-sbn1"
  PrivateSubnet2:
    Value: !Ref PrivateSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-private-sbn2"
  DatabaseSubnet0:
    Value: !Ref DatabaseSubnet0
    Export:
      Name: !Sub "${AWS::StackName}-database-sbn0"
  DatabaseSubnet1:
    Value: !Ref DatabaseSubnet1
    Export:
      Name: !Sub "${AWS::StackName}-database-sbn1"
  DatabaseSubnet2:
    Value: !Ref DatabaseSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-database-sbn2"