AWSTemplateFormatVersion: '2010-09-09'
Resources:
  FirstVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
      - Key: Name
        Value: FirstVPC
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: FirstVPC-IGW
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref FirstVPC
      InternetGatewayId: !Ref InternetGateway
  FrontendRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: AttachGateway
    Properties:
      VpcId: !Ref FirstVPC
      Tags:
      - Key: Name
        Value: FirstVPC-FrontendRoute
  FrontendRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref FrontendRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  FrontendSubnet1:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: ap-northeast-1a
      MapPublicIpOnLaunch: 'true'
      VpcId: !Ref FirstVPC
      Tags:
      - Key: Name
        Value: FirstVPC-FrontendSubnet1
  FrontendSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref FrontendSubnet1
      RouteTableId: !Ref FrontendRouteTable
  FrontendSubnet2:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: ap-northeast-1c
      MapPublicIpOnLaunch: 'true'
      VpcId: !Ref FirstVPC
      Tags:
      - Key: Name
        Value: FirstVPC-FrontendSubnet2
  FrontendSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref FrontendSubnet2
      RouteTableId: !Ref FrontendRouteTable
  BackendSubnet1:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      CidrBlock: 10.0.11.0/24
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref FirstVPC
      Tags:
      - Key: Name
        Value: FirstVPC-BackendSubnet1
  BackendSubnet2:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      CidrBlock: 10.0.12.0/24
      AvailabilityZone: ap-northeast-1c
      VpcId: !Ref FirstVPC
      Tags:
      - Key: Name
        Value: FirstVPC-BackendSubnet2
  DatastoreSubnet1:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      CidrBlock: 10.0.21.0/24
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref FirstVPC
      Tags:
      - Key: Name
        Value: FirstVPC-DatastoreSubnet1
  DatastoreSubnet2:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      CidrBlock: 10.0.22.0/24
      AvailabilityZone: ap-northeast-1c
      VpcId: !Ref FirstVPC
      Tags:
      - Key: Name
        Value: FirstVPC-DatastoreSubnet2
Outputs:
  VPC:
    Value: !Ref FirstVPC
    Export:
      Name: !Sub "${AWS::StackName}-VPC"
  FrontendSubnet1:
    Value: !Ref FrontendSubnet1
    Export:
      Name: !Sub "${AWS::StackName}-FrontendSubnet1"
  FrontendSubnet2:
    Value: !Ref FrontendSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-FrontendSubnet2"
  BackendSubnet1:
    Value: !Ref BackendSubnet1
    Export:
      Name: !Sub "${AWS::StackName}-BackendSubnet1"
  BackendSubnet2:
    Value: !Ref BackendSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-BackendSubnet2"
  DatastoreSubnet1:
    Value: !Ref DatastoreSubnet1
    Export:
      Name: !Sub "${AWS::StackName}-DatastoreSubnet1"
  DatastoreSubnet2:
    Value: !Ref DatastoreSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-DatastoreSubnet2"